table Dim_MarginBasis
	lineageTag: a91a2bc3-6440-4a9a-84d9-3c3053e09d12

	column MarginBasis
		dataType: string
		lineageTag: 7f7b070e-09fb-47d7-9710-331ffe9d13d7
		summarizeBy: none
		sortByColumn: SortOrder
		sourceColumn: MarginBasis
	column SortOrder
		dataType: int64
		formatString: 0
		lineageTag: 47134cf8-813c-4954-bf3f-cdd5a3bc1e6e
		summarizeBy: none
		sourceColumn: SortOrder

	partition Dim_MarginBasis = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(TargetFolder & "\Dim_MarginBasis.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"MarginBasis", type text}, {"SortOrder", Int64.Type}})
				in
				    #"Changed Type"
