table Dim_Census
	lineageTag: 3a404332-50ca-4f09-9534-416b91879c90

	column Population
		dataType: string
		lineageTag: 5b3daccb-f9e9-4f35-8ca9-c6d79d171e4c
		summarizeBy: none
		sortByColumn: SortOrder
		sourceColumn: Population
	column SortOrder
		dataType: int64
		formatString: 0
		lineageTag: 7dda27b3-5f69-430e-a92e-415f46b49b81
		summarizeBy: none
		sourceColumn: SortOrder
	column Description
		dataType: string
		lineageTag: 7ae3232c-c2bd-47de-b2da-3fcb1065c6c4
		summarizeBy: none
		sourceColumn: Description

	partition Dim_Census = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(TargetFolder & "\Dim_Census.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Population", type text}, {"SortOrder", Int64.Type}, {"Description", type text}})
				in
				    #"Changed Type"
