table Fact_MonthlyTrend
	lineageTag: 6a42128d-2b1b-450f-b0a2-fd20398dd951

	column Population
		dataType: string
		lineageTag: e2dfe168-0666-48ef-a43c-bc3b651b146d
		summarizeBy: none
		sourceColumn: Population
	column MonthLabel
		dataType: string
		lineageTag: b7dc262e-a30a-43a8-940c-28884777d5af
		summarizeBy: none
		sourceColumn: MonthLabel
	column MonthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 15af9ecf-b782-4229-bbee-e38b4ecc47ee
		summarizeBy: none
		sourceColumn: MonthDate
	column Revenue
		dataType: double
		formatString: 0.000
		lineageTag: d64ac8ac-1d87-4fac-a01f-5301f19de154
		summarizeBy: sum
		sourceColumn: Revenue
	column Cost
		dataType: double
		formatString: 0.000
		lineageTag: b091664a-ae75-4eef-bb8e-136526fbece3
		summarizeBy: sum
		sourceColumn: Cost
	column MarginPct
		dataType: double
		formatString: 0.0%
		lineageTag: 413847f7-773a-4b18-bb16-91e4d43e2d13
		summarizeBy: none
		sourceColumn: MarginPct
	measure 'Trend Revenue' = SUM('Fact_MonthlyTrend'[Revenue])
		formatString: $#,##0.0,,"M"
		lineageTag: fda3ca26-0887-4280-9a44-19603654e640
	measure 'Trend Cost' = SUM('Fact_MonthlyTrend'[Cost])
		formatString: $#,##0.0,,"M"
		lineageTag: 74d24669-1556-4034-83e1-d38c918ef320
	measure 'Trend Margin %' = 
		VAR Rev = [Trend Revenue]
		VAR Cost = [Trend Cost]
		RETURN DIVIDE(Rev - Cost, Rev, 0)
		formatString: 0.0%
		lineageTag: dc3d42be-516f-4d38-a62c-07fbd53672b3

	partition Fact_MonthlyTrend = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(TargetFolder & "\Fact_MonthlyTrend.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Population", type text}, {"MonthLabel", type text}, {"MonthDate", type date}, {"Revenue", type number}, {"Cost", type number}, {"MarginPct", type number}})
				in
				    #"Changed Type"
